### ISSUE TITLE
Invite you to try FslexFsyacc

### ISSUE THREAD

**Issue by xp44mm** [teo-tsirpanis/Farkle#20]
Compiler/Parser programming enthusiasts, I am very pleased to invite you to try a new series of lex/yacc tools. 

Fslex is a code generator that uses regular expression syntax as a rule to generate a function, which divides the input token sequence into groups at a higher level. The Fslex is often used to remove redundant delimiters, add omitted delimiters or other syntax components, and so on. The Fslex is also used to determine context somewhere in the stream.

Fsyacc is a code generator that use BNF productions and precedences as a rule to generate a function, which resolves the input token sequence to an abstract syntax tree.

Why use the package?

- You can use your existing handwriting tokenizer.

- This package uses standard lex/yacc syntax to minimize your learning costs.

- fslex/fsyacc generates respectively an independent, side-effect-free function that can be called flexibly.

- The method of generating code is simple, without command lines and without the need to configure projects.

- The result code is data-driven and highly readable.

- Flexiblely compose of tokenize, regular expressions, BNF technology.

The project is hosted on [GitHub](https://github.com/xp44mm/FslexFsyacc) where you can report issues, fork the project and submit pull requests.

**Comment by teo-tsirpanis** [comment]
Hello, and thanks for notifying me, I like other people having the same interest in parsing as I have, it makes a great opportunity to learn from each other. I am wondering though, what advantages does your project offer over Farkle? Let me address your bullet points:

* Farkle allows custom tokenizers as well, and there is [a well-commented example that implements an indentation-sensitive grammar](https://github.com/teo-tsirpanis/Farkle/blob/master/sample/Farkle.Samples.FSharp/IndentBased.fs).
* Farkle uses standard F# _and C#_ code to minimize your learning costs even more, provide IntelliSense, and real-time syntax error checking for free, and allow you to craft your language in any way imaginable.
* Farkle does not generate source code. The entire logic for building the LALR and DFA tables lies within the `Farkle` library. It also can seamlessly [generate these grammar tables ahead of time](https://teo-tsirpanis.github.io/Farkle/the-precompiler.html), to provide the start-up performance characteristics and early error reporting of real parser generators like yours. But that is a totally optional feature.
* ⬆
* ⬆
* Didn't exactly understand the last one, but regexes, terminals and nonterminals in Farkle are first-class objects that can be easily composed. Moreover Farkle's tokenizers and post-processors (the objects that convert the tokens and productions to useful objects) are easily replaceable and usable on their own, if that's what you meant.

**Comment by xp44mm** [comment]
I've given your project a star and will find time to learn about it in the future.

My last point is that both fslex and fsyacc generate a pure function with no side effects, so they can be composed flexibly. 

fslex generates the analyze function

```F#
analyze: seq<'token> -> seq<'a>
```

and fsyacc generates the parse function

```F#
parse: seq<'token> -> 'ast
```

With your introduction, our project may be somewhat similar. Not generating source code may be friendlier to the parser designer. The way the source code is generated may have a little benefit to startup performance.

**Comment by teo-tsirpanis** [comment]
I think I now understand what you meant @xp44mm and I am going to close this issue.

Thanks for trying Farkle and I hope it serves you well. Don't hesitate to open an issue or discussion if you have any question.
