### ISSUE TITLE
Question about multiple Regexs and IndistinguishableSymbols2

### ISSUE THREAD

**Issue by kaashyapan** [teo-tsirpanis/Farkle#25]
Hi
Thanks for sharing Farkle.
Apologies if it is a stupid question.
I am trying to parse a schema file to an AST.
I have a problem with declaring multiple Regexs in a single df. 
If this is not allowed can you a different way of doing it?
Below is my fsx file.

```fsharp
#r "nuget: Farkle, 6.4.0"

open Farkle
open Farkle.Builder
open Farkle.Builder.Regex


let makeDesigntime () =
    let t' = Terminal.Literal("type")

    let typeName =
        Regex.regexString "[A-Z][a-z0-9]+"
        |> terminal "typeName" (T(fun _ data -> data.ToString()))
        
    let enumVal =
        concat [
            Regex.regexString "[A-Z]+"
            concat [
                Regex.Literal "="
                Regex.chars PredefinedSets.Number |> plus
            ] |> optional
        ]
        |> star
        |> terminal "enumVal" (T(fun _ data -> data.ToString()))
    
    
    let enumDefT = Nonterminal.Create<string>("EnumDef")
    enumDefT.SetProductions(
        !& "enum" .>> "{" .>>. (enumVal) .>> "}" |> asIs
    )
    
    let bareT = Nonterminal.Create<string>("Bare")
    bareT.SetProductions(
        !%t' .>>. typeName .>>. enumDefT => (fun k v -> k + v)
    )
        
    bareT
    |> DesigntimeFarkle.caseSensitive true
    |> DesigntimeFarkleOperators.many

let convert: RuntimeFarkle<list<string>> =
    makeDesigntime () |> RuntimeFarkle.build

"""
type UserType enum { 
    USR
    RUS = 99
}
"""
|> RuntimeFarkle.parseString convert 
|> printfn "%A"
```
I get a builderror.
```
  (BuildError
     [IndistinguishableSymbols2
        (set
           [Choice1Of4 (Terminal (1u, "typeName"));
            Choice1Of4 (Terminal (4u, "enumVal"))], "AA");
```

**Comment by teo-tsirpanis** [comment]
Hello @kaashyapan and thanks for using Farkle. Your error means that there are strings that the regexes of both `typeName` and `enumVal` can match, and Farkle can't figure out which of them it encountered.

`AA` is one minimal example Farkle identified that could correspond to either a `typeName` or an `enumVal`. Farkle anticipated that if it sees an `AA`, it won't be sure which terminal it is, and thus failed.

**Comment by kaashyapan** [comment]
Ok Thanks for explaining.
I need 2 regexes, Alphanumeric for the type identifier and a capitalized constant string for the enum value.
The regexes are not mutually exclusive but I thought it would pick the right one based on the context but it seems they need to be unique at build time.

Is there another way to achieve this ? I couldn't find a sample which is similar.
```
type UserType enum {  // type name alphanumeric
    USR               //  Upper case string constant
    RUS = 99
}
```

**Comment by teo-tsirpanis** [comment]
I will take a look into this. In the meantime, you can make the error messages more user-friendly by changing the end of your snippet like this:

``` fsharp
|> RuntimeFarkle.parseString convert
|> function
| Ok x -> printfn "%A" x
| Error x -> printfn "%O" x
```

It would print the following:

```
Building the grammar failed:
Cannot distinguish between symbols: typeName, enumVal. The regexes of both can match 'AA' for example.
Cannot distinguish between symbols: typeName, enumVal. The regexes of both can match 'TY' for example.
Cannot distinguish between symbols: typeName, enumVal. The regexes of both can match 'TYP' for example.
Cannot distinguish between symbols: typeName, enumVal. The regexes of both can match 'EN' for example. 
Cannot distinguish between symbols: typeName, enumVal. The regexes of both can match 'ENU' for example.
```

**Comment by teo-tsirpanis** [comment]
Here's what I found:

First you have to change the order of functions. `caseSensitive` and other functions like `addLineComment` and `autoWhitespace` must be called at the end. `many` was called after that and so Farkle could not see it. This is how it should be done (`DesigntimeFarkleOperators` is automatically opened):

``` fsharp
bareT
|> many
|> DesigntimeFarkle.caseSensitive true
```

The other thing is that the `enumVal` terminal is too complex; it must be decomposed into one terminal for the enum name, one for the enum's value (you can use the `Terminals.int` function), and combined using nonterminals, like you did with `EnumDef` and `Bare`.

Let me know how it went.

**Comment by kaashyapan** [comment]
My problem is that I cant figure out a way to Regex match a variable name which is alphanumeric and a value assignment to that variable that is numeric. The match always returns the alphanumeric which is a superset of the numeric field.

```fsharp
#r "nuget: Farkle, 6.4.0"

open Farkle
open Farkle.Builder
open Farkle.Builder.Regex


let makeDesigntime () =

    let int = 
        Terminal.Create("Integer", T(fun _ data -> int (data.ToString())), Regex.chars PredefinedSets.Number |> atLeast 1)
    let varName = 
        Terminal.Create("Var Name", T(fun _ data -> data.ToString()), Regex.chars PredefinedSets.AlphaNumeric |> atLeast 1)

    let bareT = Nonterminal.Create<string>("Bare")
    bareT.SetProductions(
        empty.Extend(varName).Append("=").Extend(int).Finish(fun x v -> x.ToString() + v.ToString()),
        empty.Extend(varName).Finish(fun x -> x.ToString())
    )
        
    bareT
    |> many1
    |> DesigntimeFarkle.caseSensitive true


let convert: RuntimeFarkle<list<string>> =
    makeDesigntime () |> RuntimeFarkle.build

"""
    USD 
    GBP = 99

"""
|> RuntimeFarkle.parseString convert
|> function
| Ok x -> printfn "%A" x
| Error x -> printfn "%O" x
``` 

```
Building the grammar failed: Cannot distinguish between symbols: 'Var Name', Integer. The regexes of both can match '0' for example.
```

**Comment by teo-tsirpanis** [comment]
The `Var Name` terminal must not start with a number. This limitation is in fact common to many programming languages to avoid confusing the tokenizer.

Here's how it could be implemented, there are no more build errors after this:

``` fsharp
let varName = 
    regexString "[A-Za-z][A-Za-z0-9]*"
    |> terminal "Var Name" (T(fun _ data -> data.ToString()))
```

**Comment by kaashyapan** [comment]
Thanks for your time.
